INSERT INTO books_table (award, title, author, year) VALUES
--> 'The Andrew Carnegie Medals for Excellence in Fiction'
('The Andrew Carnegie Medals for Excellence in Fiction', 'Lost Children Archive', 'Valeria Luiselli', 2020)
('The Andrew Carnegie Medals for Excellence in Fiction', 'The Great Believers', 'Rebecca Makkai', 2019)
('The Andrew Carnegie Medals for Excellence in Fiction', 'Manhattan Beach', 'Jennifer Egan', 2018)
('The Andrew Carnegie Medals for Excellence in Fiction', 'The Underground Railroad', 'Colson Whitehead', 2017)
('The Andrew Carnegie Medals for Excellence in Fiction', 'The Sympathizer', 'Viet Thanh Nguyen', 2016),
('The Andrew Carnegie Medals for Excellence in Fiction', 'All the Light We Cannot See', 'Anthony Doerr', 2015),
('The Andrew Carnegie Medals for Excellence in Fiction', 'The Goldfinch', 'Donna Tartt', 2014),
('The Andrew Carnegie Medals for Excellence in Fiction', 'Canada', 'Richard Ford', 2013),
('The Andrew Carnegie Medals for Excellence in Fiction', 'The Forgotten Waltz', 'Anne Enright', 2012)

--> 'The Booker Prize'
('The Booker Prize', 'Shuggie Bain', 'Douglas Stuart', 2020),
('The Booker Prize', 'The Testaments', 'Magaret Atwood' , 2019),
('The Booker Prize', 'Milkman','Anna Burns', 2018),
('The Booker Prize', 'Something To Answer For', 'PH Newby', 1969),
('The Booker Prize', 'The Elected Member', 'Bernice Rubens', 1970)
('The Booker Prize', 'In a Free State', 'VS Naipaul', 1971),
('The Booker Prize', 'G', 'John Berger', 1972),
('The Booker Prize', 'The Siege of Krishnapur', 'JG Farrell', 1973),
('The Booker Prize', 'Holiday', 'Stanley Middleton', 1974),
('The Booker Prize', 'The Conservationist', 'Nadine Gordimer', 1974),
('The Booker Prize', 'Heat and Dust', 'Ruth Prawer Jhabvala', 1975),
('The Booker Prize', 'Saville', 'David Storey', 1976),
('The Booker Prize', 'Staying On', 'Paul Scott', 1977),
('The Booker Prize', 'The Sea, The Sea', 'Iris Murdoch', 1978),
('The Booker Prize', 'Offshore', 'Penelope Fitzgerald', 1979),
('The Booker Prize', 'Rites of Passage', 'William Golding', 1980),
('The Booker Prize', 'Midnight''s Children', 'Salman Rushdie', 1981)
('The Booker Prize', 'Schindler''s Ark', 'Thomas Keneally', 1982),
('The Booker Prize', 'Life & Times of Michael K', 'JM Coetzee', 1983),
('The Booker Prize', 'Hotel du Lac', 'Anita Brookner', 1984),
('The Booker Prize', 'The Bone People', 'Keri Hulme', 1985),
('The Booker Prize', 'The Old Devils', 'Kingsley Amis', 1986),
('The Booker Prize', 'Moon Tiger', 'Penelope Lively', 1987),
('The Booker Prize', 'Oscar and Lucinda', 'Peter Carey', 1988),
('The Booker Prize', 'The Remains of the Day', 'Kazuo Ishiguro', 1989),
('The Booker Prize', 'Possession', 'AS Byatt', 1990),
('The Booker Prize', 'The Famished Road', 'Ben Okri', 1991),
('The Booker Prize', 'Sacred Hunger', 'Barry Unsworth', 1992),
('The Booker Prize', 'The English Patient', 'Michael Ondaatje', 1992),
('The Booker Prize', 'Paddy Clarke Ha Ha Ha', 'Roddy Doyle', 1993),
('The Booker Prize', 'How Late It Was, How Late', 'James Kelman', 1994),
('The Booker Prize', 'The Ghost Road', 'Pat Barker', 1995),
('The Booker Prize', 'Last Orders', 'Graham Swift', 1996),
('The Booker Prize', 'The God of Small Things', 'Arundhati Roy', 1997),
('The Booker Prize', 'Amsterdam', 'Ian McEwan', 1998),
('The Booker Prize', 'Disgrace', 'JM Coetzee', 1999),
('The Booker Prize', 'The Blind Assassin', 'Margaret Atwood', 2000),
('The Booker Prize', 'True History of the Kelly Gang', 'Peter Carey', 2001),
('The Booker Prize', 'Life of Pi', 'Yann Martel', 2002),
('The Booker Prize', 'Vernon God Little', 'DBC Pierre', 2003),
('The Booker Prize', 'The Line of Beauty', 'Alan Hollinghurst', 2004),
('The Booker Prize', 'The Sea', 'John Banville', 2005),
('The Booker Prize', 'The Inheritance of Loss', 'Kiran Desai', 2006),
('The Booker Prize', 'The Gathering', 'Anne Enright', 2007),
('The Booker Prize', 'The White Tiger', 'Aravind Adiga', 2008),
('The Booker Prize', 'Wolf Hall', 'Hilary Mantel', 2009),
('The Booker Prize', 'Troubles', 'JG Farrell "Lost Booker"', 1970),
('The Booker Prize', 'The Finkler Question', 'Howard Jacobson', 2010),
('The Booker Prize', 'The Sense of an Ending', 'Julian Barnes', 2011),
('The Booker Prize', 'Bring Up the Bodies', 'Hilary Mantel', 2012),
('The Booker Prize', 'Lincoln in the Bardo', 'George Saunders', 2017),
('The Booker Prize', 'The Sellout', 'Paul Beatty', 2016),
('The Booker Prize', 'A Brief History of Seven Killings', 'Marlon James', 2015),
('The Booker Prize', 'The Narrow Road to the Deep North', 'Richard Flanagan', 2014),
('The Booker Prize', 'The Luminaries', 'Eleanor Catton', 2013)

--> 'National Book Award for Fiction'
('National Book Award for Fiction', 'Interior Chinatown', 'Charles Yu', 2020),
('National Book Award for Fiction', 'Trust Exercise', 'Susan Choi', 2019),
('National Book Award for Fiction', 'The Friend', 'Sigrid Nunez', 2018),
('National Book Award for Fiction', 'The Man with the Golden Arm', 'Nelson Algren', 1950),
('National Book Award for Fiction', 'Collected Stories of William Faulkner', 'William Faulkner', 1951),
('National Book Award for Fiction', 'From Here to Eternity', 'James Jones', 1952),
('National Book Award for Fiction', 'Invisible Man', 'Ralph Ellison', 1953),
('National Book Award for Fiction', 'The Adventures of Augie March', 'Saul Bellow', 1954),
('National Book Award for Fiction', 'A Fable', 'William Faulkner', 1955),
('National Book Award for Fiction', 'Ten North Frederick', 'John O''Hara', 1956),
('National Book Award for Fiction', 'The Field of Vision', 'Wright Morris', 1957),
('National Book Award for Fiction', 'The Wapshot Chronicle', 'John Cheever', 1958),
('National Book Award for Fiction', 'The Magic Barrel', 'Bernard Malamud', 1959),
('National Book Award for Fiction', 'Goodbye, Columbus', 'Philip Roth', 1960),
('National Book Award for Fiction', 'The Waters of Kronos', 'Conrad Richter', 1961),
('National Book Award for Fiction', 'The Moviegoer', 'Walker Percy', 1962),
('National Book Award for Fiction', 'Morte d''Urban', 'J. F. Powers', 1963),
('National Book Award for Fiction', 'The Centaur', 'John Updike', 1964),
('National Book Award for Fiction', 'Herzog', 'Saul Bellow', 1965),
('National Book Award for Fiction', 'The Collected Stories of Katherine Anne Porter', 'Katherine Anne Porter', 1966),
('National Book Award for Fiction', 'The Fixer', 'Bernard Malamud', 1967),
('National Book Award for Fiction', 'The Eighth Day', 'Thornton Wilder', 1968),
('National Book Award for Fiction', 'Steps', 'Jerzy Kosiński', 1969),
('National Book Award for Fiction', 'Them', 'Joyce Carol Oates', 1970),
('National Book Award for Fiction', 'Mr. Sammler''s Planet', 'Saul Bellow', 1971),
('National Book Award for Fiction', 'The Complete Stories', 'Flannery O''Connor', 1972),
('National Book Award for Fiction', 'Chimera', 'John Barth', 1973),
('National Book Award for Fiction', 'Augustus', 'John Williams', 1973),
('National Book Award for Fiction', 'Gravity''s Rainbow', 'Thomas Pynchon', 1974),
('National Book Award for Fiction', 'A Crown of Feathers and Other Stories', 'Isaac Bashevis Singer', 1974),
('National Book Award for Fiction', 'Dog Soldiers', 'Robert Stone', 1975),
('National Book Award for Fiction', 'The Hair of Harold Roux', 'Thomas Williams', 1975),
('National Book Award for Fiction', 'J R', 'William Gaddis', 1976),
('National Book Award for Fiction', 'The Spectator Bird', 'Wallace Stegner', 1977),
('National Book Award for Fiction', 'Blood Tie', 'Mary Lee Settle', 1978),
('National Book Award for Fiction', 'Going After Cacciato', 'Tim O''Brien', 1979),
('National Book Award for Fiction', 'Sophie''s Choice', 'William Styron', 1980),
('National Book Award for Fiction', 'The World According to Garp', 'John Irving', 1980),
('National Book Award for Fiction', 'Plains Song: For Female Voices', 'Wright Morris', 1981),
('National Book Award for Fiction', 'The Stories of John Cheever', 'John Cheever', 1981),
('National Book Award for Fiction', 'Rabbit Is Rich', 'John Updike', 1982),
('National Book Award for Fiction', 'So Long, See You Tomorrow', 'William Maxwell', 1982),
('National Book Award for Fiction', 'The Color Purple', 'Alice Walker', 1983),
('National Book Award for Fiction', 'The Collected Stories of Eudora Welty', 'Eudora Welty', 1983),
('National Book Award for Fiction', 'Victory Over Japan', 'Ellen Gilchrist', 1984),
('National Book Award for Fiction', 'White Noise', 'Don DeLillo', 1985),
('National Book Award for Fiction', 'World''s Fair', 'E. L. Doctorow', 1986),
('National Book Award for Fiction', 'Paco''s Story', 'Larry Heinemann', 1987),
('National Book Award for Fiction', 'Paris Trout', 'Pete Dexter', 1988),
('National Book Award for Fiction', 'Spartina', 'John Casey', 1989),
('National Book Award for Fiction', 'Middle Passage', 'Charles Johnson', 1990),
('National Book Award for Fiction', 'Mating', 'Norman Rush', 1991),
('National Book Award for Fiction', 'All the Pretty Horses', 'Cormac McCarthy', 1992),
('National Book Award for Fiction', 'The Shipping News', 'E. Annie Proulx', 1993),
('National Book Award for Fiction', 'A Frolic of His Own', 'William Gaddis', 1994),
('National Book Award for Fiction', 'Sabbath''s Theater', 'Philip Roth', 1995),
('National Book Award for Fiction', 'Ship Fever and Other Stories', 'Andrea Barrett', 1996),
('National Book Award for Fiction', 'Cold Mountain', 'Charles Frazier', 1997),
('National Book Award for Fiction', 'Charming Billy', 'Alice McDermott', 1998),
('National Book Award for Fiction', 'Waiting', 'Ha Jin', 1999),
('National Book Award for Fiction', 'In America', 'Susan Sontag', 2000),
('National Book Award for Fiction', 'The Corrections', 'Jonathan Franzen', 2001),
('National Book Award for Fiction', 'Three Junes', 'Julia Glass', 2002),
('National Book Award for Fiction', 'The Great Fire', 'Shirley Hazzard', 2003),
('National Book Award for Fiction', 'The News from Paraguay', 'Lily Tuck', 2004),
('National Book Award for Fiction', 'Europe Central', 'William T. Vollmann', 2005),
('National Book Award for Fiction', 'The Echo Maker', 'Richard Powers', 2006),
('National Book Award for Fiction', 'Tree of Smoke', 'Denis Johnson', 2007),
('National Book Award for Fiction', 'Shadow Country', 'Peter Matthiessen', 2008),
('National Book Award for Fiction', 'Let the Great World Spin', 'Colum McCann', 2009),
('National Book Award for Fiction', 'Lord of Misrule', 'Jaimy Gordon', 2010),
('National Book Award for Fiction', 'Salvage the Bones', 'Jesmyn Ward', 2011),
('National Book Award for Fiction', 'The Round House', 'Louise Erdrich', 2012),
('National Book Award for Fiction', 'The Good Lord Bird', 'James McBride', 2013),
('National Book Award for Fiction', 'Redeployment', 'Phil Klay', 2014),
('National Book Award for Fiction', 'Fortune Smiles', 'Adam Johnson', 2015),
('National Book Award for Fiction', 'The Underground Railroad', 'Colson Whitehead', 2016),
('National Book Award for Fiction', 'Sing, Unburied, Sing', 'Jesmyn Ward', 2017)

--> 'The National Book Critics Circle Award'

('The National Book Critics Circle Award', 'Ragtime', 'E. L. Doctorow', 1975),
('The National Book Critics Circle Award', 'October Light', 'John Gardner', 1976),
('The National Book Critics Circle Award', 'Song of Solomon', 'Toni Morrison', 1977),
('The National Book Critics Circle Award', 'The Stories of John Cheever', 'John Cheever', 1978),
('The National Book Critics Circle Award', 'The Year of the French', 'Thomas Flanagan,' 1979),
('The National Book Critics Circle Award', 'The Transit of Venus', 'Shirley Hazzard', 1980),
('The National Book Critics Circle Award', 'Rabbit Is Rich', 'John Updike', 1981),
('The National Book Critics Circle Award', 'George Mills', 'Stanley Elkin', 1982),
('The National Book Critics Circle Award', 'Ironweed', 'William Kennedy', 1983),
('The National Book Critics Circle Award', 'Love Medicine', 'Louise Erdrich', 1984),
('The National Book Critics Circle Award', 'The Accidental Tourist', 'Anne Tyler', 1985),
('The National Book Critics Circle Award', 'Kate Vaiden', 'Reynolds Price', 1986),
('The National Book Critics Circle Award', 'The Counterlife', 'Philip Roth', 1987),
('The National Book Critics Circle Award', 'The Middleman and Other Stories', 'Bharati Mukherjee', 1988),
('The National Book Critics Circle Award', 'Billy Bathgate', 'E. L. Doctorow', 1989),
('The National Book Critics Circle Award', 'Rabbit at Rest', 'John Updike', 1990),
('The National Book Critics Circle Award', 'A Thousand Acres', 'Jane Smiley', 1991),
('The National Book Critics Circle Award', 'All the Pretty Horses', 'Cormac McCarthy', 1992),
('The National Book Critics Circle Award', 'A Lesson Before Dying', 'Ernest J. Gaines', 1993),
('The National Book Critics Circle Award', 'The Stone Diaries', 'Carol Shields', 1994),
('The National Book Critics Circle Award', 'Mrs. Ted Bliss', 'Stanley Elkin', 1995),
('The National Book Critics Circle Award', 'Women in Their Beds', 'Gina Berriault', 1996),
('The National Book Critics Circle Award', 'The Blue Flower', 'Penelope Fitzgerald', 1997),
('The National Book Critics Circle Award', 'The Love of a Good Woman', 'Alice Munro', 1998),
('The National Book Critics Circle Award', 'Motherless Brooklyn', 'Jonathan Lethem', 1999),
('The National Book Critics Circle Award', 'Being Dead', 'Jim Crace', 2000),
('The National Book Critics Circle Award', 'Austerlitz', 'W.G. Sebald', 2001),
('The National Book Critics Circle Award', 'Atonement', 'Ian McEwan', 2002),
('The National Book Critics Circle Award', 'The Known World', 'Edward P. Jones', 2003),
('The National Book Critics Circle Award', 'Gilead', 'Marilynne Robinson', 2004),
('The National Book Critics Circle Award', 'The March', 'E. L. Doctorow', 2005),
('The National Book Critics Circle Award', 'The Inheritance of Loss', 'Kiran Desai', 2006),
('The National Book Critics Circle Award', 'The Brief Wondrous Life of Oscar Wao', 'Junot Diaz', 2007),
('The National Book Critics Circle Award', '2666', 'Roberto Bolaño', 2008),
('The National Book Critics Circle Award', 'Wolf Hall', 'Hilary Mantel', 2009),
('The National Book Critics Circle Award', 'A Visit from the Goon Squad', 'Jennifer Egan', 2010),
('The National Book Critics Circle Award', 'Binocular Vision: New and Selected Stories', 'Edith Pearlman', 2011),
('The National Book Critics Circle Award', 'Billy Lynn''s Long Halftime Walk', 'Ben Fountain', 2012),
('The National Book Critics Circle Award', 'Americanah', 'Chimamanda Ngozi Adichie', 2013),
('The National Book Critics Circle Award', 'Lila', 'Marilynne Robinson', 2014),
('The National Book Critics Circle Award', 'The Sellout', 'Paul Beatty', 2015),
('The National Book Critics Circle Award', 'LaRose', 'Louise Erdrich', 2016),
('The National Book Critics Circle Award', 'Improvement', 'Joan Silber', 2017),
('The National Book Critics Circle Award', 'Milkman', 'Anna Burns', 2018),
('The National Book Critics Circle Award', 'Everything Inside', 'Edwidge Danticat', 2019)

--> 'The PEN/Bellwether Prize for Socially Engaged Fiction'
('The PEN/Bellwether Prize for Socially Engaged Fiction', 'Hydrangeas of New Jessup', 'Jamila Minnicks Gleason', 2020)
('The PEN/Bellwether Prize for Socially Engaged Fiction', 'At the Edge of the Haight', 'Katherine Seligman', 2019)
('The PEN/Bellwether Prize for Socially Engaged Fiction', 'The Leavers', 'Lisa Ko', 2016)
('The PEN/Bellwether Prize for Socially Engaged Fiction', 'And West Is West', 'Ron Childress', 2014)
('The PEN/Bellwether Prize for Socially Engaged Fiction', 'Good Kings Bad Kings', 'Susan Nussbaum', 2012)
('The PEN/Bellwether Prize for Socially Engaged Fiction', 'Running the Rift', 'Naomi Benaron', 2010)
('The PEN/Bellwether Prize for Socially Engaged Fiction', 'The Girl Who Fell From the Sky', 'Heidi W. Durrow', 2008)
('The PEN/Bellwether Prize for Socially Engaged Fiction', 'Mudbound', 'Hillary Jordan', 2006)
('The PEN/Bellwether Prize for Socially Engaged Fiction', 'Correcting the Landscape', 'Marjorie Kowalski Cole', 2004)
('The PEN/Bellwether Prize for Socially Engaged Fiction', 'The Book of Dead Birds', 'Gayle Brandeis', 2002)
('The PEN/Bellwether Prize for Socially Engaged Fiction', 'Kissing the Virgin’s Mouth', 'Donna Gershten', 2000)

--> 'The PEN/Faulkner Award for Fiction'



--> 'The Pultizer Prize for Fiction'
('The Pultizer Prize for Fiction', 'The Nickel Boys', 'Colson Whitehead', 2020),
('The Pultizer Prize for Fiction', 'The Overstory', 'Richard Powers', 2019),
('The Pultizer Prize for Fiction', 'Less', 'Andrew Sean Greer', 2018)
('The Pultizer Prize for Fiction', 'His Family', 'Ernest Poole', 1918),
('The Pultizer Prize for Fiction', 'The Magnificent Ambersons', 'Booth Tarkington', 1919),
('The Pultizer Prize for Fiction', 'The Age of Innocence', 'Edith Wharton', 1921)
('The Pultizer Prize for Fiction', 'Alice Adams', 'Booth Tarkington', 1922), 
('The Pultizer Prize for Fiction', 'One of Ours', 'Willa Cather', 1923),
('The Pultizer Prize for Fiction', 'The Able McLaughlins', 'Margaret Wilson', 1924),
('The Pultizer Prize for Fiction', 'So Big', 'Edna Ferber', 1925),
('The Pultizer Prize for Fiction', 'Arrowsmith', 'Sinclair Lewis (declined)', 1926),
('The Pultizer Prize for Fiction', 'Early Autumn', 'Louis Bromfield', 1927),
('The Pultizer Prize for Fiction', 'The Bridge of San Luis Rey', 'Thornton Wilder', 1928),
('The Pultizer Prize for Fiction', 'Scarlet Sister Mary', 'Julia Peterkin', 1929),
('The Pultizer Prize for Fiction', 'Laughing Boy', 'Oliver La Farge', 1930),
('The Pultizer Prize for Fiction', 'Years of Grace', 'Margaret Ayer Barnes', 1931),
('The Pultizer Prize for Fiction', 'The Good Earth', 'Pearl S. Buck', 1932),
('The Pultizer Prize for Fiction', 'The Store', 'Thomas Sigismund Stribling', 1933),
('The Pultizer Prize for Fiction', 'Lamb in His Bosom', 'Caroline Pafford Miller', 1934),
('The Pultizer Prize for Fiction', 'Now in November', 'Josephine Winslow Johnson', 1935),
('The Pultizer Prize for Fiction', 'Honey in the Horn', 'Harold L. Davis', 1936),
('The Pultizer Prize for Fiction', 'Gone with the Wind', 'Margaret Mitchell', 1937),
('The Pultizer Prize for Fiction', 'The Late George Apley', 'John Phillips Marquand', 1938),
('The Pultizer Prize for Fiction', 'The Yearling', 'Marjorie Kinnan Rawlings', 1939),
('The Pultizer Prize for Fiction', 'The Grapes of Wrath', 'John Steinbeck', 1940),
('The Pultizer Prize for Fiction', 'In This Our Life', 'Ellen Glasgow', 1942),
('The Pultizer Prize for Fiction', 'Dragon''s Teeth', 'Upton Sinclair', 1943),
('The Pultizer Prize for Fiction', 'Journey in the Dark', 'Martin Flavin', 1944),
('The Pultizer Prize for Fiction', 'A Bell for Adano', 'John Hersey', 1945),
('The Pultizer Prize for Fiction', 'All the King''s Men', 'Robert Penn Warren', 1947),
('The Pultizer Prize for Fiction', 'Tales of the South Pacific', 'James A. Michener', 1948),
('The Pultizer Prize for Fiction', 'Guard of Honor', 'James Gould Cozzens', 1949),
('The Pultizer Prize for Fiction', 'The Way West', 'A. B. Guthrie Jr.', 1950),
('The Pultizer Prize for Fiction', 'The Town', 'Conrad Richter', 1951),
('The Pultizer Prize for Fiction', 'The Caine Mutiny', 'Herman Wouk', 1952),
('The Pultizer Prize for Fiction', 'The Old Man and the Sea', 'Ernest Hemingway', 1953),
('The Pultizer Prize for Fiction', 'A Fable', 'William Faulkner', 1955),
('The Pultizer Prize for Fiction', 'Andersonville', 'MacKinlay Kantor', 1956),
('The Pultizer Prize for Fiction', 'A Death in the Family', 'James Agee', 1958),
('The Pultizer Prize for Fiction', 'The Travels of Jaimie McPheeters', 'Robert Lewis Taylor', 1959),
('The Pultizer Prize for Fiction', 'Advise and Consent', 'Allen Drury', 1960),
('The Pultizer Prize for Fiction', 'To Kill a Mockingbird', 'Harper Lee', 1961),
('The Pultizer Prize for Fiction', 'The Edge of Sadness', 'Edwin O''Connor', 1962),
('The Pultizer Prize for Fiction', 'The Reivers', 'William Faulkner', 1963),
('The Pultizer Prize for Fiction', 'The Keepers of the House', 'Shirley Ann Grau', 1965),
('The Pultizer Prize for Fiction', 'The Collected Stories of Katherine Anne Porter', 'Katherine Anne Porter', 1966),
('The Pultizer Prize for Fiction', 'The Fixer', 'Bernard Malamud', 1967),
('The Pultizer Prize for Fiction', 'The Confessions of Nat Turner', 'William Styron', 1968),
('The Pultizer Prize for Fiction', 'House Made of Dawn', 'N. Scott Momaday', 1969),
('The Pultizer Prize for Fiction', 'The Collected Stories of Jean Stafford', 'Jean Stafford', 1970),
('The Pultizer Prize for Fiction', 'Angle of Repose', 'Wallace Stegner', 1972),
('The Pultizer Prize for Fiction', 'The Optimist''s Daughter', 'Eudora Welty', 1973),
('The Pultizer Prize for Fiction', 'The Killer Angels', 'Michael Shaara', 1975),
('The Pultizer Prize for Fiction', 'Humboldt''s Gift', 'Saul Bellow', 1976),
('The Pultizer Prize for Fiction', 'Elbow Room', 'James Alan McPherson', 1978),
('The Pultizer Prize for Fiction', 'The Stories of John Cheever', 'John Cheever', 1979),
('The Pultizer Prize for Fiction', 'The Executioner''s Song', 'Norman Mailer', 1980),
('The Pultizer Prize for Fiction', 'A Confederacy of Dunces', 'John Kennedy Toole', 1981),
('The Pultizer Prize for Fiction', 'Rabbit Is Rich', 'John Updike', 1982),
('The Pultizer Prize for Fiction', 'The Color Purple', 'Alice Walker', 1983),
('The Pultizer Prize for Fiction', 'Ironweed,' 'William Kennedy', 1984),
('The Pultizer Prize for Fiction', 'Foreign Affairs', 'Alison Lurie', 1985),
('The Pultizer Prize for Fiction', 'Lonesome Dove', 'Larry McMurtry', 1986),
('The Pultizer Prize for Fiction', 'A Summons to Memphis', 'Peter Taylor', 1987),
('The Pultizer Prize for Fiction', 'Beloved', 'Toni Morrison', 1988),
('The Pultizer Prize for Fiction', 'Breathing Lessons', 'Anne Tyler', 1989),
('The Pultizer Prize for Fiction', 'The Mambo Kings Play Songs of Love', 'Oscar Hijuelos', 1990),
('The Pultizer Prize for Fiction', 'Rabbit at Rest', 'John Updike', 1991),
('The Pultizer Prize for Fiction', 'A Thousand Acres', 'Jane Smiley', 1992),
('The Pultizer Prize for Fiction', 'A Good Scent from a Strange Mountain', 'Robert Olen Butler', 1993),
('The Pultizer Prize for Fiction', 'The Shipping News', 'E. Annie Proulx', 1994),
('The Pultizer Prize for Fiction', 'The Stone Diaries', 'Carol Shields', 1995),
('The Pultizer Prize for Fiction', 'Independence Day', 'Richard Ford', 1996),
('The Pultizer Prize for Fiction', 'Martin Dressler: The Tale of an American Dreamer', 'Steven Millhauser', 1997),
('The Pultizer Prize for Fiction', 'American Pastoral', 'Philip Roth', 1998),
('The Pultizer Prize for Fiction', 'The Hours', 'Michael Cunningha', 1999),
('The Pultizer Prize for Fiction', 'Interpreter of Maladies', 'Jhumpa Lahiri', 2000),
('The Pultizer Prize for Fiction', 'The Amazing Adventures of Kavalier & Clay', 'Michael Chabon', 2001),
('The Pultizer Prize for Fiction', 'Empire Falls', 'Richard Russo', 2002),
('The Pultizer Prize for Fiction', 'Middlesex', 'Jeffrey Eugenides', 2003),
('The Pultizer Prize for Fiction', 'The Known World', 'Edward P. Jones', 2004),
('The Pultizer Prize for Fiction', 'Gilead', 'Marilynne Robinson', 2005),
('The Pultizer Prize for Fiction', 'March', 'Geraldine Brooks', 2006),
('The Pultizer Prize for Fiction', 'The Road', 'Cormac McCarthy', 2007),
('The Pultizer Prize for Fiction', 'The Brief Wondrous Life of Oscar Wao', 'Junot Díaz', 2008),
('The Pultizer Prize for Fiction', 'Olive Kitteridge', 'Elizabeth Strout', 2009),
('The Pultizer Prize for Fiction', 'Tinkers', 'Paul Harding', 2010),
('The Pultizer Prize for Fiction', 'A Visit from the Goon Squad', 'Jennifer Egan', 2011),
('The Pultizer Prize for Fiction', 'The Orphan Master''s Son', 'Adam Johnson', 2013),
('The Pultizer Prize for Fiction', 'The Goldfinch', 'Donna Tartt', 2014),
('The Pultizer Prize for Fiction', 'All the Light We Cannot See', 'Anthony Doerr', 2015),
('The Pultizer Prize for Fiction', 'The Sympathizer', 'Viet Thanh Nguyen', 2016)